{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cwl",
    "module": "time-statistics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "time-statistics-1.0.0.jar",
          "url": "time-statistics-1.0.0.jar",
          "size": 16477,
          "sha512": "bacbd2697f0ab8dca5099198710aef0064d364e7679ea695d9b6cce8a669f0085eb073dc5cb9c897f08da44ce153da5b13b67ad6370fc27a68b7eb23a939a025",
          "sha256": "a7116bfc0fb95484d3b191853964564ae16b53c3f6dfc727d49f3efe390014e0",
          "sha1": "fb3aa84449b42f7501db7fd130648315e9ed8b14",
          "md5": "1d5b26710e20c4b3a9aba2946556c909"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "time-statistics-1.0.0.jar",
          "url": "time-statistics-1.0.0.jar",
          "size": 16477,
          "sha512": "bacbd2697f0ab8dca5099198710aef0064d364e7679ea695d9b6cce8a669f0085eb073dc5cb9c897f08da44ce153da5b13b67ad6370fc27a68b7eb23a939a025",
          "sha256": "a7116bfc0fb95484d3b191853964564ae16b53c3f6dfc727d49f3efe390014e0",
          "sha1": "fb3aa84449b42f7501db7fd130648315e9ed8b14",
          "md5": "1d5b26710e20c4b3a9aba2946556c909"
        }
      ]
    }
  ]
}
